/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_lkspencer_kirk_face_api_FaceLib */

#ifndef _Included_com_lkspencer_kirk_face_api_FaceLib
#define _Included_com_lkspencer_kirk_face_api_FaceLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_lkspencer_kirk_face_api_FaceLib
 * Method:    StartLearning
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_lkspencer_kirk_face_api_FaceLib_StartLearning
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_lkspencer_kirk_face_api_FaceLib
 * Method:    StopLearning
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_lkspencer_kirk_face_api_FaceLib_StopLearning
  (JNIEnv *, jclass);

/*
 * Class:     com_lkspencer_kirk_face_api_FaceLib
 * Method:    DetectMatch
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_lkspencer_kirk_face_api_FaceLib_DetectMatch
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_lkspencer_kirk_face_api_FaceLib
 * Method:    HelloJni
 * Signature: ()[C
 */
JNIEXPORT jstring JNICALL Java_com_lkspencer_kirk_face_api_FaceLib_HelloJni
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
